#!/usr/bin/env bash
# Write launch.sh on the **company** (SoT). Thin redirect on package root.
#
# Usage:
#   write_company_launch.sh --company-dir DEST --package-root PKG
#
# DEST = …/<slug>-company (nested or external)
# PKG  = product package / project root (owns .grok/ adapters)
set -euo pipefail

HOLDING_INSTALL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CORE="$HOLDING_INSTALL/launch_company.sh"
COMPANY_DIR=""
PKG_ROOT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --company-dir) COMPANY_DIR="${2:-}"; shift 2 ;;
    --package-root) PKG_ROOT="${2:-}"; shift 2 ;;
    *) echo "unknown: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$COMPANY_DIR" || ! -f "$CORE" ]]; then
  echo "error: need --company-dir and $CORE" >&2
  exit 2
fi
if [[ -z "$PKG_ROOT" ]]; then
  echo "error: --package-root is required (project root that owns .grok/)" >&2
  exit 2
fi

COMPANY_DIR="$(cd "$COMPANY_DIR" && pwd)"
PKG_ROOT="$(cd "$PKG_ROOT" && pwd)"
REL_COMP="$(python3 -c "import os; print(os.path.relpath('$COMPANY_DIR', '$PKG_ROOT'))")"

# Company SoT launch.sh — ROOT baked to package (adapters cwd)
cat > "$COMPANY_DIR/launch.sh" <<EOF
#!/usr/bin/env bash
# Generated by write_company_launch.sh — company SoT entry (always CEO).
# Docs: agents-holding docs/ceo-launch-and-children.md
set -euo pipefail
COMP="\$(cd "\$(dirname "\$0")" && pwd)"
ROOT="$PKG_ROOT"
CORE="$CORE"
HOP="\$COMP/system/skills/defaults/marlin-hop/scripts/handoff_child.py"
FRESH_ARGS=()
POS=()
for a in "\$@"; do
  case "\$a" in
    --fresh) FRESH_ARGS+=(--fresh) ;;
    -h|--help)
      echo "Usage: ./$REL_COMP/launch.sh <grok|claude|codex|merge> [--fresh] [child?] [prompt]"
      exit 0
      ;;
    *) POS+=("\$a") ;;
  esac
done
set -- "\${POS[@]+"\${POS[@]}"}"
[[ \$# -ge 1 ]] || {
  echo "Usage: ./$REL_COMP/launch.sh <grok|claude|codex|merge> [--fresh] [child?] [prompt]" >&2
  exit 2
}
MODE="\$1"; shift
if [[ \$# -ge 1 && -f "\$HOP" ]] && python3 "\$HOP" "\$1" --print-path >/dev/null 2>&1; then
  CDIR="\$(python3 "\$HOP" "\$1" --print-path)"; shift
  COMP="\$CDIR"
  if [[ "\$(basename "\$(dirname "\$CDIR")" )" == ".agents" ]]; then
    ROOT="\$(cd "\$CDIR/../.." && pwd)"
  fi
fi
PROMPT="\$*"
exec bash "\$CORE" --company-dir "\$COMP" --root "\$ROOT" "\${FRESH_ARGS[@]+"\${FRESH_ARGS[@]}"}" "\$MODE" \${PROMPT:+"\$PROMPT"}
EOF
chmod +x "$COMPANY_DIR/launch.sh"
echo "[write_company_launch] company SoT: $COMPANY_DIR/launch.sh"
echo "[write_company_launch] package root (adapters): $PKG_ROOT"

# Thin redirect at package root
mkdir -p "$PKG_ROOT"
cat > "$PKG_ROOT/launch.sh" <<EOF
#!/usr/bin/env bash
# Thin redirect → company SoT ($REL_COMP/launch.sh)
exec "\$(cd "\$(dirname "\$0")" && pwd)/$REL_COMP/launch.sh" "\$@"
EOF
chmod +x "$PKG_ROOT/launch.sh"
echo "[write_company_launch] thin redirect: $PKG_ROOT/launch.sh → ./$REL_COMP/launch.sh"

# Keep AI/company launcher out of product git
GI="$PKG_ROOT/.gitignore"
if [[ -f "$GI" ]]; then
  grep -qxF 'launch.sh' "$GI" 2>/dev/null || echo 'launch.sh' >> "$GI"
elif [[ -d "$PKG_ROOT" ]]; then
  printf '%s\n' '# Local company launcher redirect (not product source)' 'launch.sh' > "$GI"
fi
